name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      env1: arn:aws:iam::787878:role/ci-ew1
      env2: arn:aws:iam::787878:role/cd-ew1
  
    strategy:
      matrix:
        short_region: [cn-1]
        include:
          - short_region: cn-1
            ci-role-to-assume: arn:aws:iam::787878:role/ci-ew1
            cd-role-to-assume: arn:aws:iam::787878:role/cd-ew1
            
      
    outputs:
      registry: ${{ steps.test.outputs.arr }}

    steps:
      - uses: actions/checkout@v3
      
      - name: echo test
        run: |
          echo ${{ github.ref == 'refs/heads/master' && matrix.ci-role-to-assume || matrix.cd-role-to-assume }}

      - name: Run a one-line script
        id: test
        working-directory: .
        run: chmod +x ./test.sh && ./test.sh ${{ matrix.short_region }} ${{ matrix.role-to-assume }} ${{ github.sha }}

  test-result:
    runs-on: ubuntu-latest
    needs:
      - build
      
    strategy:
      matrix:
        version: ${{ fromJson(needs.build.outputs.registry) }}
    steps:
      - name: Run a multi-line script
        run: |
          echo Get output from before step
          echo ${{ matrix.version }}

