name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        short_region: [cn-1]
        
    outputs:
      registries: ${{ steps.test.outputs.arr }}

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        id: test
        working-directory: .
        run: chmod +x ./test.sh && ./test.sh ${{ matrix.short_region }} ${{ github.sha }}

  test-result:
    runs-on: ubuntu-latest
    needs:
      - build
      
    strategy:
      matrix:
        short: [ "${{ needs.build.outputs.registries }}" ]
    steps:
      - name: Run a multi-line script
        env:
          input: ${{ needs.build.outputs.registries }}
        run: |
          echo Get output from before step
          echo ${{ matrix.short }}

